### ISSUE TITLE
602, The incoming request cannot be validated, Failed to create passkey credentials

### ISSUE THREAD

**Issue by federicomalagoni** [Djsmk123/flutter_credential_manager_compose#23]
**Describe the bug**
When I try to register a passkey the library keep show me this error:

602, The incoming request cannot be validated, Failed to create passkey credentials

**To Reproduce**
1. Changed domain from the example project.
2. Inserted the username and the password.
3. Clicked "Register with pass key"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Android
 - Flutter version 3.22.3

**Smartphone (please complete the following information):**
 - Nexus 6 API 33

**Additional context**
I'm using the example app provided by you.
I've already uploaded the .assetlinks file on my domain.
Check it out here:
https://dr-safety-dms-test.azurewebsites.net/.well-known/assetlinks.json

**Comment by Djsmk123** [comment]
https://dr-safety-dms-test.azurewebsites.net/.well-known/assetlinks.json
following assets link json contain handling only "delegate_permission/common.handle_all_urls".
Use following as example
```
 {
        "relation": [
            "delegate_permission/common.handle_all_urls",
            "delegate_permission/common.get_login_creds"
        ],
        "target": {
            "namespace": "android_app",
            "package_name": "com.smkwinner.cred_manager.credential_manager_example",
            "sha256_cert_fingerprints": [
                <SHA26>
            ]
        }
    }
```

**Comment by federicomalagoni** [comment]
Hello, I've changed the file as you suggested but I keep struggle with the same error:

602, The incoming request cannot be validated, Failed to create passkey credentials #23



<img width="913" alt="Screenshot 2024-08-26 at 15 36 36" src="https://github.com/user-attachments/assets/53acb952-02c9-4410-b773-8124e751fa45">

**Comment by federicomalagoni** [comment]
> https://dr-safety-dms-test.azurewebsites.net/.well-known/assetlinks.json following assets link json contain handling only "delegate_permission/common.handle_all_urls". Use following as example
> 
> ```
>  {
>         "relation": [
>             "delegate_permission/common.handle_all_urls",
>             "delegate_permission/common.get_login_creds"
>         ],
>         "target": {
>             "namespace": "android_app",
>             "package_name": "com.smkwinner.cred_manager.credential_manager_example",
>             "sha256_cert_fingerprints": [
>                 <SHA26>
>             ]
>         }
>     }
> ```

wrong package_name. solved, thanks for that answer it was the answer.
