### ISSUE TITLE
[feat] google button flow

### ISSUE THREAD

**Issue by wildsylvan** [Djsmk123/flutter_credential_manager_compose#25]
it'd be nice to have access to the [button flow](https://developer.android.com/identity/sign-in/credential-manager-siwg#trigger-siwg) as well 😁

p.s. thanks a lot for the package btw!

**Comment by Djsmk123** [comment]
Yeah it would be. Would you like to pick these let know?.
I will assign you if you want this

**Comment by wildsylvan** [comment]
thanks. i will submit a pr when i find the time 👍

**Comment by Djsmk123** [comment]
Thanks for pr. Iwill test this and merge after review

**Comment by Djsmk123** [comment]
Merge and published changes.
