### ISSUE TITLE
[Question] is it reliable to use this in prod?

### ISSUE THREAD

**Issue by Sliman-Baghouri** [Djsmk123/flutter_credential_manager_compose#30]
Hi, i wanted to open a discussion but couldn't find the tab for it. 

First, thank you for this awesome package. I wanted to ask you is it safe to use this reliably on production? 

Thanks again.

**Comment by Djsmk123** [comment]
Yes it is safe to use in production but only android its only limitations.

**Comment by Sliman-Baghouri** [comment]
Thanks a bunch
