### ISSUE TITLE
How to handle iOS ?

### ISSUE THREAD

**Issue by dleurs** [Djsmk123/flutter_credential_manager_compose#4]
Hello,

Any advice on how to implement the same thing for iOS ?

I will try with autofillHints 

- https://medium.com/@1998.singh.amarjit/save-credentials-autofill-credentials-in-flutter-33058295dd9d
- https://api.flutter.dev/flutter/material/TextField/autofillHints.html

**Comment by Djsmk123** [comment]
Google has not released anything yet for iOS related to jetpack credentials manager.
As of now we can integrate this https://medium.com/@1998.singh.amarjit/save-credentials-autofill-credentials-in-flutter-33058295dd9d

**Comment by kalyanchandra48** [comment]
Can we handle the pop-up overlay update password?

I want the popup only after the response,Is it Possible?

**Comment by Djsmk123** [comment]
I don't think so. @dleurs  Anything you like to add here?

> @Djsmk123 Can we handle the pop-up overlay update password?
> 
> I want the popup only after the response, ![Screenshot 2024-01-24 at 11 56 33 AM](https://private-user-images.githubusercontent.com/81020495/299205551-cb0a587b-6e8b-43ad-a3a3-99cf56af5eab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTg2MDAsIm5iZiI6MTcwNjE5ODMwMCwicGF0aCI6Ii84MTAyMDQ5NS8yOTkyMDU1NTEtY2IwYTU4N2ItNmU4Yi00M2FkLWEzYTMtOTljZjU2YWY1ZWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1NTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZTI3ODE2NWZhOTRiY2M5N2E5YzFlZjkwMWVjZGFmNzAzYzcwMWMxMDgzYjU0ODJmOWQ5NmI4MWEyMGI2NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pMARgl5_lP95Ty3uyFMqrWZ4RwGQdmrm9mqNBPsSoj8) Is it Possible?

**Comment by SunilKividor** [comment]
anything on how to do the same for ios ?
