### ISSUE TITLE
Auto fill from website

### ISSUE THREAD

**Issue by Djsmk123** [Djsmk123/flutter_credential_manager_compose#5]
## Changes Required

- [ ] Update Readme.md
- [ ] Configure required changes on native code
    - For reference:
https://developer.android.com/training/sign-in/passkeys

**Comment by SunilKividor** [comment]
@Djsmk123 I am not able to save the google credentials after i select the account with passkey . I am getting an unhandled exception. Can you please help me ?

**Comment by SunilKividor** [comment]
I am getting a 504 error with a message : activity is cancelled by the user. Login failed. I have added everything what is mentioned in the read me but still i am facing this issue. Can you please help me figure this out ?

**Comment by Djsmk123** [comment]
Hi @SunilKividor, I have not yet integrate passkey in this package.
But you can refer this documentation for integration
https://developer.android.com/training/sign-in/passkeys

**Comment by SunilKividor** [comment]
hey @Djsmk123 can i set the nonce ,sign in to google and get the google id token? Can you please help me which method i need to call ?

**Comment by Djsmk123** [comment]
@SunilKividor you can checkout new version and let me know if you are getting same error.
I am closing this issue.
**Feel free to reopen this.**

**Comment by SunilKividor** [comment]
@Djsmk123 do you know any resources or package for something similar for IOS ?
